### ISSUE TITLE
Find voting system for Oslo Pride Song Of The Year

### ISSUE THREAD

**Issue by hexjelly** [oslopride/oslopride.no#183]
(limit to one vote per person/device)

Try to find out if there's anything we can use and embed easily,  rather than creating our own functionality.

**Comment by boyeborg** [comment]
I've gone through quite some systems, but can't find anything that seems to work nicely. [SurveyLegend](https://www.surveylegend.com/) was the only simple solution I could find that did what we wanted, but it looks kind of crap. I also tried [Typeform](typeform.com), but they don't have any way of limiting the submissions to one per person/device unfortunately. On their help page they (Typeform) suggest using their embed SDK and do some cookie/localstorage check.
You can see a preview/test I did on embeds here: https://preview.oslopride.no/a/test-pride-song-2021-test

**Comment by boyeborg** [comment]
The most elegant/best solution would perhaps be to create a poll type in sanity, where people can create polls (kind of like articles). Where each poll contains a question and between two and five answers. Each answer also has a vote count that's un-editable from the sanity web interface (if that's possible). Then we only need to allow polls as a block on packes (and in articles), add some react&css to make it look nice, plus some localstorage/cookie magic to prevent multiple submissions.

**Comment by luk-str** [comment]
Hey 👋

Not sure how crucial security is for this poll but wouldn't anything based on cookies/localstorage be very easy to game?
I suppose a user could just open a private window and submit as many votes as they like, no technical skills required 😬

If limiting votes is important then probably there has to be some kind of a login system (?)
To not make it too complicated maybe it'd be a good idea to just use something like google forms? It's pretty much universal and most users know how to use it and would be able to log in.

**Comment by boyeborg** [comment]
Hi @luk-str, and thanks for the contributions!

I totally agree with you, but as far as my understanding they don't want any login. Last year we used google forms without authentication, allowing people to vote as many times as they liked. That did not work very vell as you might imagine 🤦. They still don't want any login, but would like some kind of prevention. Currently it's believed that localstorage might be sufficient since people would need to take an active action to vote several times (by clearing localstorage, using private windows or different browsers etc). However, it's not certain this actually is true, so I'm very open for suggestions!

At the top of my mind I can see four different degrees of prevention:

1. No prevention: everyone can vote as many times they like (did not work well)
2. Browser besed prevention: localstorage/cookies prevent the same browser from voting several times
3. Browser + IP based prevention: Same as number 2, but includes storing and checking new votes agains the (anonymised) IP addresses of existing votes, preventing the same IP to vote multiple times.
4. Some sort of login

Number 2 is what I proposed above. In my opinion, number 3 is starting to look like too much job for such a small thing (in perspective of the whole festival), and can still be bypassed (with VPN, or just by using a cellular internet connection where IP addresses changes all the time). So if number 2 is not good enough, I lean towards number 4, since we don't need to implement anything, just use Google Forms like last year, but with login.

The nice thing about Google Forms is that most people probably already are logged in with their google account, and therefor would not feel like it was a login. However, for principal reasons I don't love using Google, as that would force all voters to be tracked by google. But on the other side, we are still (sadly) using Google Analytics on Oslo Pride anyways, so that argument might not hold water.

The coolest solution for a login-system would maybe be to use something like a magic link system, where people just enter their email address, receives an email with a link, clicks the link, and then they can vote (once). However, that would also require us to create a whole new system, and would probably not be worth the time.

**Comment by boyeborg** [comment]
(sorry for the wall of text 😅 but really looking forward to hear your thoughts)

**Comment by luk-str** [comment]
A lot of valid points @boyeborg!

I'm totally in the camp of avoiding google tracking as much as possible so yeah, while Google Forms is an easy way out, it might be worth looking at other options!

Some kind of magic link might be cool but I suppose it's still essentially a login system, just based on e-mail and it also means you're collecting users' e-mail addresses and storing them somewhere. Also sounds like a lot of extra work like you say.

Looks like it's either log-in or just accept that the system may be gamed and try to make cheating as much of a pain in the ass as possible 😄 All things considered, I think if there's a cookie thing, maybe some kind of ip limitations and something like a captcha that's slightly annoying to solve, it could be enough to discourage multi-voting for 90% of the users. It's not the oscars so I guess the world won't collapse if 10% give multiple votes 🐶

I found this thing called [Crowdsignal](https://crowdsignal.com/) that seems to tick all of the boxes + gives good customization options. Have you looked at that as well? 🙂
