### ISSUE TITLE
Hero content can overflow and cover following content

### ISSUE THREAD

**Issue by hexjelly** [oslopride/oslopride.no#191]
This *seems* to possibly stem from us setting a fixed height on the hero (or is it in the `Header` component? 🤷). Only really happens on smaller mobile screens that maybe no one actually uses but... If we ever were to put other stuff in the front page header (live stream embed or other stuff), it might cause issues again.

This might require quite a bit of CSS rewriting and cleaning up 😬 (or maybe not!)

![image](https://user-images.githubusercontent.com/435283/108591269-29cc9b00-7368-11eb-9607-5d3dabcd5b98.png)

**Comment by luk-str** [comment]
This is definitely an issue and I can confirm that it affects me as a user as I'm still on a tiny iPhone SE screen 👴

As you rightly point out, the problem is the fixed height provided every time to the hero component. Ideally the hero component's height should be based off of it's content. That way it stays flexible and the code won't have to be changed every time an editor makes changes to the content in Sanity.
There could still be a flexible bottom padding/margin that can be set on individual pages so that the styling can be varied between pages, but I think the height itself should definitely follow the content.

Rewriting the hero component might be a bit complex as the height parameter is used inside the component itself in a couple of different ways but I think it will ultimately save a lot of coding time in the future 🙃

**Comment by luk-str** [comment]
By the way, since I'm up to date with the hero component, I can try and get this fixed if you like 😉

**Comment by hexjelly** [comment]
Definitely feel free to do that, I recognize it's been a while since I did anything in the code myself (and I didn't work on the hero component before), so if you have some ideas of how to solve it that would be very welcomed!

**Comment by luk-str** [comment]
Alright, on it 🕺🏻

**Comment by hexjelly** [comment]
I vaguely remember there being some absolutely positioned things involved, and I'm not sure that's even necessary anymore (?), which might simplify things
